import { useEffect, useState } from "react";
import countryData from "./countries.json";

// Only the (tiny) country list is bundled. States and cities live in
// public/geo/*/<ISO>.json, generated by scripts/build-geo.mjs, and are fetched
// for just the country a visitor picks instead of shipping the 7.7 MB city
// database to every page.
export const COUNTRIES = countryData.map(([name, isoCode]) => ({ name, isoCode }));

const isoByName = new Map(COUNTRIES.map((c) => [c.name, c.isoCode]));

// ISO code -> flag emoji via regional indicator symbols (native, no data file).
export const countryFlag = (countryName) => {
  const isoCode = isoByName.get(countryName);
  if (!isoCode) return "";
  return [...isoCode.toUpperCase()]
    .map((ch) => String.fromCodePoint(127397 + ch.charCodeAt(0)))
    .join("");
};

const cache = new Map();
const load = (kind, iso, fallback) => {
  const key = `${kind}/${iso}`;
  if (!cache.has(key)) {
    const p = fetch(`/geo/${kind}/${iso}.json`)
      .then((r) => (r.ok ? r.json() : fallback))
      .catch(() => {
        cache.delete(key); // retry next time on a network failure
        return fallback;
      });
    cache.set(key, p);
  }
  return cache.get(key);
};

export const statesForCountry = async (countryName) => {
  const iso = isoByName.get(countryName);
  if (!iso) return [];
  return (await load("states", iso, [])).map(([name, isoCode]) => ({ name, isoCode }));
};

// Falls back to all cities in the country when it has no state-level data
// (many small countries), or when no state has been picked yet.
export const citiesForCountry = async (countryName, stateName) => {
  const iso = isoByName.get(countryName);
  if (!iso) return [];
  const byState = await load("cities", iso, {});
  if (stateName) {
    const state = (await statesForCountry(countryName)).find((s) => s.name === stateName);
    if (state) return byState[state.isoCode] || [];
  }
  return Object.values(byState).flat();
};

// State/city dropdown options for a form; fills in once the country's file arrives.
export function useGeoOptions(country, state) {
  const [stateOptions, setStates] = useState([]);
  const [cityOptions, setCities] = useState([]);

  useEffect(() => {
    let live = true;
    setStates([]);
    if (country) statesForCountry(country).then((s) => live && setStates(s));
    return () => { live = false; };
  }, [country]);

  useEffect(() => {
    let live = true;
    setCities([]);
    if (country) citiesForCountry(country, state).then((c) => live && setCities(c));
    return () => { live = false; };
  }, [country, state]);

  return { stateOptions, cityOptions };
}
