-- =============================================================================
-- MISSING TABLES & COLUMNS — run once on MySQL production
-- Generated by comparing sap_security_expert_prod.sql with server/db.js and
-- all repository files. Safe to re-run: every statement uses IF NOT EXISTS /
-- IF NOT EXISTS column check pattern.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. MISSING TABLES
--    These tables exist in db.js (SQLite) but are absent from the prod dump.
-- -----------------------------------------------------------------------------

-- 1a. credit_activities — stores the 9 earn-activity types + their credit amounts.
--     Used by: CreditHelper.js, creditsRepository.js, AdminCreditBundles.
CREATE TABLE IF NOT EXISTS `credit_activities` (
  `id`          INT          NOT NULL AUTO_INCREMENT,
  `key`         VARCHAR(100) NOT NULL,
  `label`       VARCHAR(255) NOT NULL,
  `description` TEXT         DEFAULT '',
  `credits`     INT          NOT NULL DEFAULT 1,
  `is_active`   TINYINT(1)  NOT NULL DEFAULT 1,
  `created_at`  DATETIME     DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_ca_key` (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Seed the 9 default activities (safe to re-run)
INSERT IGNORE INTO `credit_activities` (`key`, `label`, `description`, `credits`) VALUES
  ('new_registration',  'New Registration',                     'Credits awarded when a new member registers',              10),
  ('approved_comment',  'Approved Comment',                     'Credits awarded when a comment is approved',                2),
  ('referral',          'Referral (new member registers)',      'Credits awarded when a referred member joins',              2),
  ('article_published', 'Article Published (Community Author)', 'Credits awarded when a contributed article is published',  20),
  ('podcast_guest',     'Podcast Guest',                        'Credits awarded for appearing on the podcast',             20),
  ('error_report',      'Report an Error',                      'Credits awarded when a member reports an article error',    1),
  ('complete_profile',  'Complete Profile',                     'Credits awarded when a member completes their profile',     2),
  ('product_review',    'Submit a Product Review',              'Credits awarded when a member submits a product review',    5),
  ('linkedin_share',    'LinkedIn Share',                       'Credits awarded when a member shares on LinkedIn',          5);

-- 1b. site_settings — key/value store for admin-configurable settings.
--     Used by: settingsController.js, settingsRepository.js.
CREATE TABLE IF NOT EXISTS `site_settings` (
  `key`        VARCHAR(100) NOT NULL,
  `value`      TEXT         NOT NULL,
  `updated_at` DATETIME     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO `site_settings` (`key`, `value`)
VALUES ('paywall_default_preview_paragraphs', '3');

-- 1c. member_file_downloads — tracks per-member file download access (credit-gated).
--     Used by: DownloadBlock.jsx → /api/downloads route.
CREATE TABLE IF NOT EXISTS `member_file_downloads` (
  `id`           INT          NOT NULL AUTO_INCREMENT,
  `member_id`    INT          NOT NULL,
  `file_url`     VARCHAR(500) NOT NULL,
  `credits_spent` INT         NOT NULL DEFAULT 0,
  `downloaded_at` DATETIME    DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_dld` (`member_id`, `file_url`(191)),
  KEY `idx_dld_member` (`member_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- -----------------------------------------------------------------------------
-- 2. MISSING COLUMNS ON EXISTING TABLES
-- -----------------------------------------------------------------------------

-- 2a. blogs — preview_paragraphs + preview_unit
--     Referenced in postsRepository.js UPDATE and INSERT; not in prod schema.
ALTER TABLE `blogs`
  ADD COLUMN IF NOT EXISTS `preview_paragraphs` INT DEFAULT NULL;
ALTER TABLE `blogs`
  ADD COLUMN IF NOT EXISTS `preview_unit` VARCHAR(10) DEFAULT 'blocks';

-- 2b. payment_orders — razorpay_payment_id
--     Already in prod schema — included here as a reference; skip if present.
-- ALTER TABLE `payment_orders`
--   ADD COLUMN IF NOT EXISTS `razorpay_payment_id` VARCHAR(255) DEFAULT NULL;
-- (Column confirmed present in prod dump — no action needed.)


-- -----------------------------------------------------------------------------
-- 3. MYSQL COMPATIBILITY FIXES
--    Issues found in repository files that only work on SQLite or need fixing.
-- -----------------------------------------------------------------------------

-- 3a. settingsRepository.js uses "INSERT OR REPLACE" (SQLite syntax) as a
--     fallback. In production MySQL this path is never reached because the
--     primary try block already uses ON DUPLICATE KEY UPDATE. No SQL change
--     needed here — but confirm settingsRepository.js try/catch is in place.
--     ✓ Confirmed: server/repositories/admin/settingsRepository.js wraps
--       MySQL path in try{} and SQLite path in catch{} — MySQL path runs first.

-- 3b. post_views — prod table has `ip_address` column; code only writes
--     `post_id`, `visitor_token`, `created_at` — no conflict, ip_address
--     allows NULL so inserts will succeed.

-- 3c. Unique index on post_views (post_id, visitor_token).
--     db.js creates this for SQLite. Prod dump lacks it — add it:
--     (visitor_token is longtext in prod; prefix-index required for longtext)
ALTER TABLE `post_views`
  ADD UNIQUE INDEX IF NOT EXISTS `idx_pv_dedup` (`post_id`, `visitor_token`(64));


-- -----------------------------------------------------------------------------
-- 4. PERFORMANCE INDEXES (from add_performance_indexes.sql)
--    Idempotent — skip any that already exist.
-- -----------------------------------------------------------------------------

-- blogs
ALTER TABLE `blogs`
  ADD INDEX IF NOT EXISTS `idx_blogs_slug`        (`slug`),
  ADD INDEX IF NOT EXISTS `idx_blogs_status_date` (`status`, `date`),
  ADD INDEX IF NOT EXISTS `idx_blogs_category`    (`category`),
  ADD INDEX IF NOT EXISTS `idx_blogs_author_id`   (`author_id`),
  ADD INDEX IF NOT EXISTS `idx_blogs_created_at`  (`created_at`),
  ADD INDEX IF NOT EXISTS `idx_blogs_view_count`  (`view_count`);

-- comments
ALTER TABLE `comments`
  ADD INDEX IF NOT EXISTS `idx_comments_post_status` (`post_id`, `status`);

-- post_views
ALTER TABLE `post_views`
  ADD INDEX IF NOT EXISTS `idx_post_views_post_created` (`post_id`, `created_at`);

-- members — missing columns added after initial schema
ALTER TABLE `members`
  ADD COLUMN IF NOT EXISTS `username`           VARCHAR(100) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `credit_balance`     INT          NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `referral_code`      VARCHAR(20)  DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `referred_by_code`   VARCHAR(20)  DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `profile_visibility` TINYINT(1)   NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS `is_deleted`         TINYINT(1)   NOT NULL DEFAULT 0;

ALTER TABLE `members`
  ADD INDEX IF NOT EXISTS `idx_members_email`    (`email`),
  ADD INDEX IF NOT EXISTS `idx_members_status`   (`status`),
  ADD INDEX IF NOT EXISTS `idx_members_username` (`username`);

-- post_views — ensure visitor_token column exists (prod schema may pre-date it)
ALTER TABLE `post_views`
  ADD COLUMN IF NOT EXISTS `visitor_token` VARCHAR(128) DEFAULT NULL;

-- credit / unlock
ALTER TABLE `member_blog_unlocks`
  ADD INDEX IF NOT EXISTS `idx_member_blog_unlocks_member` (`member_id`),
  ADD INDEX IF NOT EXISTS `idx_member_blog_unlocks_slug`   (`blog_slug`);

ALTER TABLE `credit_transactions`
  ADD INDEX IF NOT EXISTS `idx_credit_transactions_member` (`member_id`);
